export type ContractCopilotQATestCategory =
  | "direct_pay_rate_lookup"
  | "apd_threshold_calculation"
  | "direct_term_lookup"
  | "document_section_explanation"
  | "contract_scenario_retrieval"
  | "real_world_fb_scenarios";

export type ContractCopilotQASupportAnchor = {
  source: "PWA" | "Compensation Manual" | "Scheduler Manual";
  section?: string;
  terms?: string[];
  required?: boolean;
  role?: "primary" | "comparison" | "secondary";
};

export type ContractCopilotQATest = {
  id: string;
  question: string;
  expectedLane:
    | "direct_pay_rate_lookup"
    | "apd_threshold_calculation"
    | "direct_term_lookup"
    | "document_section_explanation"
    | "contract_scenario_retrieval";
  expectedSources: Array<"PWA" | "Compensation Manual" | "Scheduler Manual">;
  shouldUseAISynthesis: boolean;
  riskLevel: "low" | "medium" | "high" | "critical";
  category: ContractCopilotQATestCategory;
  expectedAnswerNotes: string[];
  expectedSupportIncludes?: string[];
  expectedSupportAnchors?: ContractCopilotQASupportAnchor[];
  redFlags: string[];
  complexityTags?: string[];
  mustInclude?: string[];
  mustNotInclude?: string[];
  shouldAskClarification?: boolean;
  clarificationStyle?: "none" | "single_targeted" | "grouped" | "targeted_only_if_needed";
  referenceAnswerHint?: string;
};

export const contractCopilotQATestBank: ContractCopilotQATest[] = [
  {
    id: "qa-cc-001",
    question: "What is my pay rate at year 5 captain A220?",
    expectedLane: "direct_pay_rate_lookup",
    expectedSources: ["Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "high",
    category: "direct_pay_rate_lookup",
    expectedAnswerNotes: [
      "Should return both A-220-100 and A-220-300 Year 5 Captain rates.",
      "Should not route through generic PWA retrieval.",
    ],
    redFlags: ["deterministic_mismatch", "no_contract_reference"],
  },
  {
    id: "qa-cc-002",
    question: "What is my hourly block pay rate if I'm a 5-year A220-300 Captain?",
    expectedLane: "direct_pay_rate_lookup",
    expectedSources: ["Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "critical",
    category: "direct_pay_rate_lookup",
    expectedAnswerNotes: [
      "Should return the exact Year 5 A-220-300 Captain hourly rate of $354.82/hour.",
      "Should not ask for a clarifier when seat, equipment, and longevity are already present.",
    ],
    redFlags: ["deterministic_mismatch", "unsupported_certainty"],
  },
  {
    id: "qa-cc-003",
    question: "Required reserves are 20, available is 6, can I APD?",
    expectedLane: "apd_threshold_calculation",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: false,
    riskLevel: "critical",
    category: "apd_threshold_calculation",
    expectedAnswerNotes: [
      "Should answer yes because 6 is above 25% of 20.",
      "Should stay in deterministic APD threshold calculation.",
    ],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 I.10", terms: ["available reserves", "25%", "required"], required: true, role: "primary" },
    ],
    redFlags: ["deterministic_mismatch", "unsupported_certainty"],
  },
  {
    id: "qa-cc-004",
    question: "On reserve, how do I determine ALV?",
    expectedLane: "direct_term_lookup",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "medium",
    category: "direct_term_lookup",
    expectedAnswerNotes: [
      "Should explain ALV practically and tie it to reserve guarantee.",
      "Should not drift into sick or Greenslip examples.",
    ],
    redFlags: ["topic_drift", "deterministic_mismatch"],
  },
  {
    id: "qa-cc-005",
    question: "What does Section 23 Q say?",
    expectedLane: "document_section_explanation",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: false,
    riskLevel: "high",
    category: "document_section_explanation",
    expectedAnswerNotes: [
      "Should retrieve the indexed Section 23 Q text instead of failing generically.",
      "Should not say the section text is not provided if it is indexed.",
    ],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 Q", terms: ["green slip"], required: true, role: "primary" },
    ],
    redFlags: ["no_contract_reference", "topic_drift"],
  },
  {
    id: "qa-cc-006",
    question:
      "I called in sick for one day and picked up a 3 day GS that starts that same day and continues after. How should this pay?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: [
      "Should preserve overlap-day treatment separately from remaining GS days.",
      "Should distinguish pay, credit, and sick-bank effects.",
      "Verifier should run for this scenario lane.",
    ],
    redFlags: ["topic_drift", "vague_answer", "no_contract_reference", "missing_source_warning"],
  },
  {
    id: "qa-cc-007",
    question: "Can I stack GS + APD + short call in the same day?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: [
      "Should stay cautious if source support is incomplete.",
      "Should not answer with unsupported certainty for a multi-rule stack question.",
    ],
    redFlags: ["unsupported_certainty", "topic_drift", "missing_source_warning"],
  },
  {
    id: "qa-cc-008",
    question: "I got a GS with conflict on top of a trip. How should that pay?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should stay on the GS/GSWC family and explain conflict treatment clearly."],
    redFlags: ["topic_drift", "unsupported_certainty", "missing_source_warning"],
  },
  {
    id: "qa-cc-009",
    question: "If I get a GSWC on an X-day, is that still premium pay?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should explain premium treatment for GSWC without drifting into IA."],
    redFlags: ["topic_drift", "unsupported_certainty"],
  },
  {
    id: "qa-cc-010",
    question: "I got a GS on a reserve X-day and then got removed before report. What happens to pay and credit?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should separate removal timing from premium-pay treatment."],
    redFlags: ["unsupported_certainty", "missing_source_warning", "topic_drift"],
  },
  {
    id: "qa-cc-011",
    question: "Can a GS on long call pay single pay no credit if they call me inside 18 hours?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should apply the 18-hour long-call carveout if the fact pattern matches."],
    redFlags: ["unsupported_certainty", "topic_drift"],
  },
  {
    id: "qa-cc-012",
    question: "I accepted a GS but the overlap day is also a short call day. Which rule controls first?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should ask or explain the controlling overlap fact before overclaiming."],
    redFlags: ["unsupported_certainty", "missing_source_warning"],
  },
  {
    id: "qa-cc-013",
    question: "On reserve, what is my reserve guarantee this month?",
    expectedLane: "direct_term_lookup",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "medium",
    category: "direct_term_lookup",
    expectedAnswerNotes: ["Should explain reserve guarantee practically and tie it to ALV."],
    redFlags: ["topic_drift", "deterministic_mismatch"],
  },
  {
    id: "qa-cc-014",
    question: "What is ADG for a lineholder?",
    expectedLane: "direct_term_lookup",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "medium",
    category: "direct_term_lookup",
    expectedAnswerNotes: ["Should stay in guarantee/line-value language, not sick or GS examples."],
    redFlags: ["topic_drift", "deterministic_mismatch"],
  },
  {
    id: "qa-cc-015",
    question: "What is the minimum daily guarantee on reserve?",
    expectedLane: "direct_term_lookup",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "medium",
    category: "direct_term_lookup",
    expectedAnswerNotes: ["Should answer with the reserve guarantee rule, not just reserve vs lineholder labels."],
    redFlags: ["topic_drift", "deterministic_mismatch"],
  },
  {
    id: "qa-cc-016",
    question: "How does short call pay if I never fly?",
    expectedLane: "direct_term_lookup",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "medium",
    category: "direct_term_lookup",
    expectedAnswerNotes: ["Should explain SCC / short-call pay-no-credit clearly."],
    redFlags: ["topic_drift", "deterministic_mismatch"],
  },
  {
    id: "qa-cc-017",
    question: "How is ALV used to build reserve credit guarantee?",
    expectedLane: "direct_term_lookup",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "medium",
    category: "direct_term_lookup",
    expectedAnswerNotes: ["Should connect ALV to reserve guarantee math in practical terms."],
    redFlags: ["topic_drift", "deterministic_mismatch"],
  },
  {
    id: "qa-cc-018",
    question: "My deadhead changed after report. Is that reroute or reassignment?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should stay on reroute/reassignment timing and not drift elsewhere."],
    redFlags: ["topic_drift", "unsupported_certainty", "missing_source_warning"],
  },
  {
    id: "qa-cc-019",
    question: "Crew Scheduling changed my first leg before report. Does reroute pay still apply?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should use the before-report branch directly if known."],
    redFlags: ["unsupported_certainty", "missing_source_warning"],
  },
  {
    id: "qa-cc-020",
    question: "I was reassigned before report and the duty day got longer. What should I look at for pay protection?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should explain reassignment/reroute distinction and pay-protection angle."],
    redFlags: ["topic_drift", "unsupported_certainty"],
  },
  {
    id: "qa-cc-021",
    question: "If they swap my deadhead to a later one while I'm driving in, is that reroute pay or not?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should focus on before-report vs after-report timing."],
    redFlags: ["unsupported_certainty", "topic_drift"],
  },
  {
    id: "qa-cc-022",
    question: "What if my reroute happened after report but before the first operating leg?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should remain conditional only if the controlling timing fact is still incomplete."],
    redFlags: ["unsupported_certainty", "missing_source_warning"],
  },
  {
    id: "qa-cc-023",
    question: "I called in sick on day one and my GS only overlapped that first day. How should the later GS days pay?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should separate overlap day from remaining GS days."],
    redFlags: ["topic_drift", "vague_answer", "missing_source_warning"],
  },
  {
    id: "qa-cc-024",
    question: "My GS sat fully inside my sick leave period. Is it single pay no credit or something else?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should preserve pay, credit, and bank treatment separately."],
    redFlags: ["unsupported_certainty", "missing_source_warning"],
  },
  {
    id: "qa-cc-025",
    question: "I called well and picked up flying after the sick trip ended. Does that still hit my sick bank?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should focus on overlap versus after-sick sequence."],
    redFlags: ["topic_drift", "unsupported_certainty"],
  },
  {
    id: "qa-cc-026",
    question: "If the overlap day pays one way, does the sick-bank replenishment still get handled separately?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should explicitly preserve separate pay and replenishment dimensions."],
    redFlags: ["vague_answer", "unsupported_certainty"],
  },
  {
    id: "qa-cc-027",
    question: "Required reserves were 24 and available was 5. Can I still APD?",
    expectedLane: "apd_threshold_calculation",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: false,
    riskLevel: "critical",
    category: "apd_threshold_calculation",
    expectedAnswerNotes: ["Should answer no because 5 is below 25% of 24."],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 I.10", terms: ["available reserves", "25%", "required"], required: true, role: "primary" },
    ],
    redFlags: ["deterministic_mismatch", "unsupported_certainty"],
  },
  {
    id: "qa-cc-028",
    question: "Required reserves are 12 and available is 3. Does that meet APD threshold exactly?",
    expectedLane: "apd_threshold_calculation",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: false,
    riskLevel: "critical",
    category: "apd_threshold_calculation",
    expectedAnswerNotes: ["Should answer yes because 3 is exactly 25% of 12."],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 I.10", terms: ["available reserves", "25%", "required"], required: true, role: "primary" },
    ],
    redFlags: ["deterministic_mismatch", "unsupported_certainty"],
  },
  {
    id: "qa-cc-029",
    question: "Why was my APD denied if the counts were 18 required and 5 available?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should shift into diagnostic mode instead of restating eligibility only."],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 I.10", terms: ["available reserves", "required"], required: true, role: "primary" },
    ],
    redFlags: ["topic_drift", "unsupported_certainty"],
  },
  {
    id: "qa-cc-030",
    question: "Can APD still be denied around a holiday even if the reserve threshold is met?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should mention holiday-period handling without overriding the PWA."],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 I.10", terms: ["APD", "holiday"], required: true, role: "primary" },
    ],
    redFlags: ["unsupported_certainty", "missing_source_warning"],
  },
  {
    id: "qa-cc-031",
    question: "What holidays does Section 23 I.10 talk about for APD restrictions?",
    expectedLane: "document_section_explanation",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: false,
    riskLevel: "medium",
    category: "document_section_explanation",
    expectedAnswerNotes: ["Should retrieve the relevant APD holiday restriction text if indexed."],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 I.10", terms: ["holiday", "APD"], required: true, role: "primary" },
    ],
    redFlags: ["no_contract_reference"],
  },
  {
    id: "qa-cc-032",
    question: "How does an asterisk rotation pay across the bid period crossover?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: ["Should talk about bid-period split treatment rather than generic guarantee language."],
    redFlags: ["topic_drift", "unsupported_certainty"],
  },
  {
    id: "qa-cc-033",
    question: "What does Section 4 F say about rotation guarantee?",
    expectedLane: "document_section_explanation",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "high",
    category: "document_section_explanation",
    expectedAnswerNotes: ["Should retrieve/summarize the indexed guarantee section."],
    expectedSupportAnchors: [
      { source: "PWA", section: "4 F", terms: ["rotation guarantee"], required: true, role: "primary" },
      { source: "Compensation Manual", terms: ["rotation guarantee"], required: false, role: "secondary" },
    ],
    redFlags: ["no_contract_reference", "topic_drift"],
  },
  {
    id: "qa-cc-034",
    question: "Explain Section 14 E and Example Three.",
    expectedLane: "document_section_explanation",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: false,
    riskLevel: "high",
    category: "document_section_explanation",
    expectedAnswerNotes: ["Should explain the worked example instead of drifting into generic sick leave text."],
    redFlags: ["no_contract_reference"],
  },
  {
    id: "qa-cc-035",
    question: "What is PWA 23 N?",
    expectedLane: "document_section_explanation",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: false,
    riskLevel: "medium",
    category: "document_section_explanation",
    expectedAnswerNotes: ["Should retrieve or summarize the section text if indexed."],
    redFlags: ["no_contract_reference", "topic_drift"],
  },
  {
    id: "qa-cc-036",
    question: "What is my hourly pay as a year 12 737-900 First Officer?",
    expectedLane: "direct_pay_rate_lookup",
    expectedSources: ["Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "high",
    category: "direct_pay_rate_lookup",
    expectedAnswerNotes: ["Should return the exact structured rate if present."],
    redFlags: ["deterministic_mismatch", "no_contract_reference"],
  },
  {
    id: "qa-cc-037",
    question: "What do I make as a year 3 A350 Captain?",
    expectedLane: "direct_pay_rate_lookup",
    expectedSources: ["Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "high",
    category: "direct_pay_rate_lookup",
    expectedAnswerNotes: ["Should use structured pay rows rather than generic compensation prose."],
    redFlags: ["deterministic_mismatch", "no_contract_reference"],
  },
  {
    id: "qa-cc-038",
    question: "Do I need Auto Accept on to be a harmed pilot under Section 23M7?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: [
      "Support should prioritize the Section 23 M.7 harmed-pilot / Auto Accept text.",
      "Should not lead support with generic sections like Section 1 Scope.",
    ],
    expectedSupportIncludes: ["23 M.7", "harmed", "auto accept"],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 M.7", terms: ["harmed pilot", "auto accept"], required: true, role: "primary" },
    ],
    redFlags: ["topic_drift", "missing_source_warning"],
  },
  {
    id: "qa-cc-039",
    question: "If I pick up a silver slip do I have to get above a certain amount above straight credit to get paid double? Similar to GS?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "contract_scenario_retrieval",
    expectedAnswerNotes: [
      "Support should prioritize silver slip / green slip / premium pay governing text.",
      "Should not lead with glossary or scope unless only as secondary support.",
    ],
    expectedSupportIncludes: ["silver slip", "green slip", "premium pay"],
    expectedSupportAnchors: [
      { source: "PWA", terms: ["silver slip"], required: true, role: "primary" },
      { source: "PWA", terms: ["green slip", "GS"], required: true, role: "comparison" },
      { source: "Compensation Manual", terms: ["premium pay", "trigger"], required: false, role: "secondary" },
    ],
    redFlags: ["topic_drift", "missing_source_warning"],
  },
  {
    id: "qa-cc-040",
    question: "What does Section 23 Q say?",
    expectedLane: "document_section_explanation",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: false,
    riskLevel: "high",
    category: "document_section_explanation",
    expectedAnswerNotes: ["Support should include Section 23 Q directly."],
    expectedSupportIncludes: ["23 Q"],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 Q", terms: ["green slip"], required: true, role: "primary" },
    ],
    redFlags: ["no_contract_reference"],
  },
  {
    id: "qa-cc-041",
    question: "What does Section 4 F say about rotation guarantee?",
    expectedLane: "document_section_explanation",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "high",
    category: "document_section_explanation",
    expectedAnswerNotes: ["Support should include the PWA Section 4 F material."],
    expectedSupportIncludes: ["4 F", "rotation guarantee"],
    expectedSupportAnchors: [
      { source: "PWA", section: "4 F", terms: ["rotation guarantee"], required: true, role: "primary" },
    ],
    redFlags: ["no_contract_reference", "topic_drift"],
  },
  {
    id: "qa-rw-001",
    question:
      "Hey gang! Picked up a 2-day QS on 22 April, originally ending with a DH back to ATL on 23 April. Was rerouted prior to DH (ACARS notification) for an LAX-SFO-LAX turn, then layover and DH home on 24 April (now a 3-day trip). Upon award, my PB days were applied to 24-25 April for my 2 interrupted X-days and a little bit of a PR on the 26th. CS has converted by PB back to LC on the 24th (totes legit) however my PB day didn’t get re-applied to a later date (should be Sunday?). I revert to LC upon release and now only show a PR on the 26th. When awarded, I had two full PBs plus my PR remainder. Now I have less even though I flew more and had more impact on my X-days due to the reroute. Called CS and they were polite and stated the “system” might just be behind and to submit a DART. Obviously less than ideal since the (perceived?) infraction will come and go prior to any resolution if they get it wrong. I’m seldom correct on these things so just wanted a sanity check before I confuse. TYIA. FWIW - also did not receive any notification (robot or human) for this trip award again so doesn’t look like that is fixed.",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should recognize this is a bundled PB/LC/PR/reroute/QS/notification scenario, not a single-variable question.",
      "Should separate contract treatment from system/process issues like DART and notifications.",
    ],
    redFlags: ["oversimplified_complex_scenario", "single_gating_question_only", "unsupported_policy_certainty"],
    complexityTags: ["PB", "QS", "reroute", "deadhead", "X-day interruption", "LC conversion", "PR remainder", "notification", "DART"],
    mustInclude: ["PB", "LC", "interrupted X-days", "reroute", "deadhead", "DART", "notification"],
    mustNotInclude: ["before or after report"],
    shouldAskClarification: true,
    clarificationStyle: "grouped",
  },
  {
    id: "qa-rw-002",
    question:
      "Trying to drop a May 2nd (May bid period) trip for a May 1st (April bid period) trip. I put my request in swap with the pot and getting “capped rsv days” denial. I thought iCrew doesn’t look at the coverage for the next bid period when swapping to this bid period. Am I mistaken here? Trip is actual, not qualified.",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should identify bid period crossover and reserve coverage/capped reserve day angle.",
      "Should treat actual vs qualified as a real distinction if support exists.",
    ],
    redFlags: ["oversimplified_complex_scenario", "unsupported_policy_certainty"],
    complexityTags: ["swap with pot", "capped reserve days", "reserve coverage", "bid period crossover", "actual not qualified"],
    mustInclude: ["bid period", "capped reserve", "reserve coverage", "actual", "qualified"],
    mustNotInclude: [],
    shouldAskClarification: false,
    clarificationStyle: "targeted_only_if_needed",
  },
  {
    id: "qa-rw-003",
    question: "How much notice is required for being assigned IOE? Not a new hire. Thanks",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "medium",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should focus on notice requirement and distinguish not-new-hire from other training contexts if possible.",
    ],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["IOE", "assignment notice", "training", "not new hire"],
    mustInclude: ["notice", "IOE", "not new hire"],
    mustNotInclude: [],
    shouldAskClarification: false,
    clarificationStyle: "targeted_only_if_needed",
  },
  {
    id: "qa-rw-004",
    question:
      "QS is supposed to call every pilot in category with a QS in right? Have blanket QS in. In middle of block of X days. No 30/168 or any other FAR restrictions. NYC 7ERA 0711 went out as QS at 0044. Phone never rang, no ARCOS email, notification, anything. Have been called for other QS, so I know my slip is active/ correct. Another NYC 7ERA who is on the same page of the wide report (so very similar seniority) also has blanket QS in, and didn't get a call for a QS he was eligible for as well.",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should focus on eligibility, call/notification process, and preserving evidence rather than giving only a generic QS definition.",
    ],
    redFlags: ["oversimplified_complex_scenario", "irrelevant_support_primary"],
    complexityTags: ["QS", "blanket QS", "call order", "category", "ARCOS", "notification", "X-days", "FAR legality"],
    mustInclude: ["QS", "ARCOS", "notification", "eligible", "evidence", "DART"],
    mustNotInclude: ["generic QS definition only"],
    shouldAskClarification: false,
    clarificationStyle: "targeted_only_if_needed",
  },
  {
    id: "qa-rw-005",
    question:
      "I had a fun new one this morning. I was denied a quick slip rotation (it went STOP) even though I was the senior responder to it. Why was I denied it? Because I was already awarded the exact same rotation 34 minutes earlier. I don't have the MOU in front of me. Is that a valid reason to stop a quick slip? Did they just quintuple pay for this day trip?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should identify the duplicate-award / same-rotation angle and avoid asserting the STOP reason without source support.",
    ],
    redFlags: ["unsupported_policy_certainty", "oversimplified_complex_scenario"],
    complexityTags: ["QS", "STOP", "senior responder", "duplicate award", "same rotation", "MOU", "premium pay"],
    mustInclude: ["QS", "STOP", "senior responder", "same rotation", "MOU"],
    mustNotInclude: [],
    shouldAskClarification: false,
    clarificationStyle: "targeted_only_if_needed",
  },
  {
    id: "qa-rw-006",
    question:
      "I’ve seen a lot of discussion lately about 23M7. Do you need to have Auto Accept turned on to be the “harmed pilot?” ALPA says no. Others say they are wrong. Which is it?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: true,
    riskLevel: "critical",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Support must center on Section 23M7 and the harmed-pilot / Auto Accept issue.",
    ],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 M.7", terms: ["harmed pilot", "auto accept"], required: true, role: "primary" },
    ],
    redFlags: ["irrelevant_support_primary", "unsupported_policy_certainty"],
    complexityTags: ["Section 23M7", "harmed pilot", "Auto Accept", "ALPA"],
    mustInclude: ["Auto Accept", "harmed pilot", "23M7"],
    mustNotInclude: ["Section 1 Scope"],
    shouldAskClarification: false,
    clarificationStyle: "none",
  },
  {
    id: "qa-rw-007",
    question:
      "If I pick up a silver slip do I have to get above a certain amount above straight credit to get paid double? Similar to GS?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should distinguish silver slip from GS and answer the premium/double-pay threshold question if source support exists.",
    ],
    expectedSupportAnchors: [
      { source: "PWA", terms: ["silver slip"], required: true, role: "primary" },
      { source: "PWA", terms: ["green slip", "GS"], required: true, role: "comparison" },
      { source: "Compensation Manual", terms: ["premium pay", "trigger"], required: false, role: "secondary" },
    ],
    redFlags: ["irrelevant_support_primary", "unsupported_policy_certainty"],
    complexityTags: ["silver slip", "green slip", "double pay", "straight credit", "premium threshold"],
    mustInclude: ["silver slip", "green slip", "double pay", "straight credit"],
    mustNotInclude: ["Section 1 Scope"],
    shouldAskClarification: false,
    clarificationStyle: "targeted_only_if_needed",
  },
  {
    id: "qa-rw-008",
    question:
      "I just received a notice to appear in court next month for a custody hearing that is on day 1 of a 4 day trip. Are there any protections for this scenario?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should discuss contract/process protections and documentation, not give legal advice.",
    ],
    redFlags: ["legal_advice_overreach", "unsupported_policy_certainty"],
    complexityTags: ["court", "custody hearing", "legal obligation", "day 1", "trip conflict", "protections", "known absence"],
    mustInclude: ["court", "custody hearing", "protections", "documentation"],
    mustNotInclude: ["legal advice"],
    shouldAskClarification: false,
    clarificationStyle: "targeted_only_if_needed",
  },
  {
    id: "qa-rw-009",
    question:
      "One of my rotations changed for next month (not a carryover trip). Looks like they removed a leg and now it’s a redeye…am I due anything extra?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should frame this as a future schedule change / pay-protection question, not a reroute-only answer.",
    ],
    redFlags: ["oversimplified_complex_scenario", "unsupported_policy_certainty"],
    complexityTags: ["rotation changed", "next month", "removed leg", "redeye", "pay protection", "schedule change"],
    mustInclude: ["next month", "removed leg", "redeye", "pay", "credit", "protection"],
    mustNotInclude: [],
    shouldAskClarification: true,
    clarificationStyle: "grouped",
  },
  {
    id: "qa-rw-010",
    question:
      "One of my rotations changed for next month (not a carryover trip). Looks like they removed a leg and now it’s a redeye…am I due anything extra? There is a similar 4-day going out the next day, but reserve coverage won’t allow the swap. Can the CPO essentially override the rules to process for the occasion? Would this fall under known absence policies? If so, any pay protection? I know the other option *cough*",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should address override/manual processing, reserve coverage limits, known-absence/pay-protection angle, and avoid endorsing policy abuse.",
    ],
    redFlags: ["suggests_policy_abuse", "unsupported_policy_certainty", "oversimplified_complex_scenario"],
    complexityTags: ["rotation change", "CPO", "override", "reserve coverage", "swap", "known absence", "pay protection"],
    mustInclude: ["CPO", "reserve coverage", "known absence", "pay protection"],
    mustNotInclude: ["abuse sick leave", "just call in sick"],
    shouldAskClarification: true,
    clarificationStyle: "grouped",
  },
  {
    id: "qa-rw-golden-day-lc-001",
    question:
      "golden day before first LC... golden day is defined as a hard non-fly day (PWA Section 2 A.129.) doesn't that mean you can't be assigned anything earlier than 6pm day one of LC? Or Day before worthless",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should treat the section reference as support inside an application question, not as a pure section dump.",
      "Should answer cautiously about golden day / hard non-fly day / LC assignment timing.",
    ],
    expectedSupportAnchors: [
      { source: "PWA", section: "2 A.129", terms: ["golden day", "hard non-fly day"], required: true, role: "primary" },
    ],
    redFlags: ["irrelevant_support_primary", "unsupported_policy_certainty"],
    complexityTags: ["golden day", "hard non-fly day", "LC", "assignment timing"],
    mustInclude: ["golden day", "hard non-fly day", "assignment", "day one"],
    mustNotInclude: ["Doctor", "Domestic air carrier"],
    shouldAskClarification: false,
    clarificationStyle: "targeted_only_if_needed",
  },
  {
    id: "qa-rw-wocl-8d3-001",
    question:
      "If I get assigned into WOCL after report, does 8D3 apply or is there some other pay protection rule that controls?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should not stop on question scope when the question is clearly about operational application.",
      "Should discuss WOCL, post-report assignment timing, and 8D3 cautiously from available support.",
    ],
    expectedSupportAnchors: [
      { source: "PWA", section: "8 D.3", terms: ["WOCL", "8D3"], required: true, role: "primary" },
    ],
    redFlags: ["single_gating_question_only", "vague_answer", "topic_drift"],
    complexityTags: ["WOCL", "8D3", "report", "assignment", "pay protection"],
    mustInclude: ["wocl", "8d3", "report", "assignment"],
    mustNotInclude: ["question_scope"],
    shouldAskClarification: true,
    clarificationStyle: "targeted_only_if_needed",
  },
  {
    id: "qa-rw-011",
    question:
      "Reserve pilot assigned a short call tomorrow 10am-5:10pm and a subsequent same day trip reporting at 5:10pm for a 7+36 flight (9+36 duty). Scheduling says the short call and trip remain on schedule.",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "critical",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should recognize a short-call plus same-day-trip legality and scheduling conflict question.",
    ],
    expectedSupportAnchors: [
      { section: "12", terms: ["duty period", "flight time", "legality"], required: false, role: "primary" },
      { source: "PWA", section: "23 S.9", terms: ["short call", "report"], required: false, role: "secondary" },
      { source: "Scheduler Manual", terms: ["short call", "duty period"], required: false, role: "secondary" },
    ],
    redFlags: ["unsupported_policy_certainty", "vague_answer"],
    complexityTags: ["reserve", "short call", "same-day trip", "report time", "duty", "legality", "scheduling", "assignment"],
    mustInclude: ["short call", "same-day trip", "5:10pm", "duty", "legality", "schedule"],
    mustNotInclude: ["generic short call definition only"],
    shouldAskClarification: true,
    clarificationStyle: "targeted_only_if_needed",
  },
  {
    id: "qa-rw-012",
    question: "How does QS pay if no op after report?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should treat this as a QS/no-op/after-report pay question, not only a generic definition.",
    ],
    redFlags: ["unsupported_policy_certainty", "vague_answer"],
    complexityTags: ["QS", "quick slip", "no op", "after report", "pay", "premium", "report"],
    mustInclude: ["qs", "no op", "after report", "pay"],
    mustNotInclude: ["generic qs definition only"],
    shouldAskClarification: true,
    clarificationStyle: "targeted_only_if_needed",
  },
  {
    id: "qa-rw-new-shortcall-notification-001",
    category: "real_world_fb_scenarios",
    question:
      "If I don't receive notification of a short call assignment after vacation, would it make sense to call the duty pilot 18 hours before assignment start time?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    complexityTags: ["reserve", "short call", "notification", "vacation", "non-fly day", "icrew", "micrew", "acknowledgment", "CNO"],
    expectedAnswerNotes: [
      "Should infer reserve context from the short-call assignment question and avoid asking reserve versus lineholder clarification.",
      "Should treat this as a short-call notification after vacation/non-fly-day dispute and stay cautious unless the exact notice rule is attached.",
    ],
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "23 S.9",
        terms: ["short call", "notification", "vacation", "non-fly day"],
        required: false,
        role: "primary",
      },
      {
        source: "Scheduler Manual",
        terms: ["short call", "notification", "telephone", "electronic placement", "acknowledge", "iCrew"],
        required: false,
        role: "secondary",
      },
    ],
    redFlags: ["unsupported_policy_certainty", "vague_answer"],
    mustInclude: ["short call", "notification", "vacation", "iCrew", "MiCrew", "duty pilot", "call logs"],
    mustNotInclude: ["were you reserve or lineholder", "lineholder that month"],
    shouldAskClarification: false,
    clarificationStyle: "none",
  },
  {
    id: "qa-rw-new-oe-notification-001",
    category: "real_world_fb_scenarios",
    question:
      "Searched both the SRH & TRH, plus here, and can't seem to find the current answer. What is the current requirement for OE notification? Is it a phone call, or can it be done by CNO?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["Scheduler Manual", "PWA"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    complexityTags: ["OE notification", "CNO", "phone call", "SRH", "TRH", "notification requirement"],
    expectedAnswerNotes: [
      "Should treat this as an OE/CNO notification-source question, not a Green Slip, pay, or deadhead question.",
      "Should explicitly say the exact OE notification / CNO source is missing if it cannot attach one.",
    ],
    expectedSupportAnchors: [
      {
        source: "Scheduler Manual",
        terms: ["OE", "notification", "CNO", "phone call", "SRH", "TRH"],
        required: false,
        role: "primary",
      },
      {
        source: "PWA",
        terms: ["OE", "notification"],
        required: false,
        role: "secondary",
      },
    ],
    redFlags: ["unsupported_policy_certainty", "vague_answer"],
    mustInclude: ["oe", "notification", "cno", "phone call"],
    mustNotInclude: ["green slip", "section 10", "cno is sufficient"],
    shouldAskClarification: false,
    clarificationStyle: "none",
  },
  {
    id: "qa-rw-new-001",
    category: "real_world_fb_scenarios",
    question: "Can you swap with pot into a trip that exceeds your max p/up? Max p/up was 0.0 and swapped a one day trip for a two day trip.",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["swap_with_pot", "max_pickup", "pickup_limit", "schedule_processing"],
    mustInclude: ["swap with pot", "max pickup", "system processing", "pickup limit"],
    mustNotInclude: ["always allowed", "always denied"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "23",
        terms: ["swap", "pickup", "open time"],
        required: false,
        role: "primary",
      },
      {
        source: "Scheduler Manual",
        terms: ["swap with pot", "pickup", "max pickup"],
        required: false,
        role: "secondary",
      },
    ],
    riskLevel: "medium",
    expectedAnswerNotes: ["Should treat this as swap-with-pot processing and pickup-limit analysis rather than a simple yes/no rule."],
    redFlags: ["oversimplified_complex_scenario", "unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-002",
    category: "real_world_fb_scenarios",
    question: "One of my rotations changed for next month, not a carryover trip. Looks like they removed a leg and now it’s a redeye. Am I due anything extra?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["future_rotation_change", "redeye", "removed_leg", "pay_protection"],
    mustInclude: ["rotation changed", "removed leg", "redeye", "pay or credit protection"],
    mustNotInclude: ["definitely owed extra pay"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "23",
        terms: ["rotation change", "schedule change", "pay protection"],
        required: false,
        role: "primary",
      },
    ],
    riskLevel: "high",
    expectedAnswerNotes: ["Should frame this as future schedule change and pay/credit protection, not a simple reroute answer."],
    redFlags: ["oversimplified_complex_scenario", "unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-003",
    category: "real_world_fb_scenarios",
    question: "My bank is full at 60 hours. I want to buy a vacation day for next year. Can I buy the vacation day and replace the 4:35 in the same month to keep the bank full? I tried this with the bank request and it says 4:35 requested and 0:00 awarded.",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: true,
    complexityTags: ["bank", "vacation", "buy_vacation_day", "replacement_credit"],
    mustInclude: ["bank full", "vacation day", "replacement", "0:00 awarded"],
    mustNotInclude: ["guaranteed approval"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "7",
        terms: ["vacation", "bank", "replacement"],
        required: false,
        role: "primary",
      },
    ],
    riskLevel: "medium",
    expectedAnswerNotes: ["Should focus on vacation-bank interaction and why the system may award 0:00, not promise approval."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-004",
    category: "real_world_fb_scenarios",
    question: "Driving to the airport now. How does QS pay if no-op after report? Single pay or suit-up 2 hours?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["quick_slip", "no_op", "after_report", "pay"],
    mustInclude: ["QS", "no-op after report", "single pay", "suit-up", "report"],
    mustNotInclude: ["always double pay"],
    shouldAskClarification: false,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "23",
        terms: ["Quick Slip", "QS", "report", "pay"],
        required: true,
        role: "primary",
      },
      {
        source: "Compensation Manual",
        terms: ["Quick Slip", "no-op", "suit-up", "pay"],
        required: false,
        role: "secondary",
      },
    ],
    riskLevel: "high",
    expectedAnswerNotes: ["Should compare single-pay versus suit-up treatment and stay source-limited if support is incomplete."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-005",
    category: "real_world_fb_scenarios",
    question: "After first airborne departure, Day 2 first flight is delayed and now we fly the same destination with a different scheduled flight number. Does this fall under reroute pay for this leg?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["reroute", "first_airborne", "flight_number_change", "same_destination"],
    mustInclude: ["first airborne", "different flight number", "same destination", "reroute pay"],
    mustNotInclude: ["flight number alone decides it"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "23 L",
        terms: ["reroute", "first segment airborne", "flight number"],
        required: true,
        role: "primary",
      },
      {
        source: "Compensation Manual",
        section: "23 L",
        terms: ["reroute pay"],
        required: false,
        role: "secondary",
      },
    ],
    riskLevel: "high",
    expectedAnswerNotes: ["Should explain why same destination plus changed flight number is not enough by itself to decide reroute pay."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-006",
    category: "real_world_fb_scenarios",
    question: "RRPay question. I am on reserve. I received the exact same RR on the last day two rotations in a row, but they paid different on my time card. Why? Both were ATL-SAV-ATL added to my last day and had about the same block time. The only difference was turn time. Rotations were on Apr 1 and Apr 17.",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["reserve", "reroute_pay", "rrpay", "timecard", "turn_time"],
    mustInclude: ["reserve", "RR", "last day", "turn time", "timecard"],
    mustNotInclude: ["same trip must pay the same"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "23 L",
        terms: ["reroute", "reserve", "pay"],
        required: false,
        role: "primary",
      },
      {
        source: "Compensation Manual",
        terms: ["reroute pay", "turn time", "timecard"],
        required: false,
        role: "secondary",
      },
    ],
    riskLevel: "high",
    expectedAnswerNotes: ["Should discuss why similar reroutes can pay differently if timing/turn mechanics differ."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-007",
    category: "real_world_fb_scenarios",
    question: "Can you move a reserve X-day between months if it adheres to the grouping restrictions? X-day on 28 Apr, reserve 29, 30, 01, 02. Can I swap the 28th and 2nd?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["reserve", "x_day", "between_months", "grouping_restrictions"],
    mustInclude: ["reserve X-day", "between months", "grouping restrictions", "28th and 2nd"],
    mustNotInclude: ["always allowed"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "23",
        terms: ["X-day", "reserve", "move", "grouping"],
        required: true,
        role: "primary",
      },
      {
        source: "Scheduler Manual",
        terms: ["X-day", "move", "reserve"],
        required: false,
        role: "secondary",
      },
    ],
    riskLevel: "high",
    expectedAnswerNotes: ["Should treat month crossover and grouping restrictions as the controlling factors, not answer with a blanket yes/no."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-008",
    category: "real_world_fb_scenarios",
    question: "iCrew won't let me deposit 2 hours in my bank. Only thing I can think is the SS credit doesn't count. What don't I know?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["bank", "silver_slip", "credit", "deposit"],
    mustInclude: ["bank", "deposit", "2 hours", "SS credit", "doesn't count"],
    mustNotInclude: ["SS credit always counts"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "PWA",
        terms: ["bank", "credit", "Silver Slip", "SS"],
        required: false,
        role: "primary",
      },
      {
        source: "Compensation Manual",
        terms: ["Silver Slip", "credit", "bank"],
        required: false,
        role: "secondary",
      },
    ],
    riskLevel: "medium",
    expectedAnswerNotes: ["Should explore whether SS credit is bank-eligible rather than assuming it always counts or never counts."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-009",
    category: "real_world_fb_scenarios",
    question: "Open Time Rotation built with domicile layover. Where is the reference that it is illegal? PWA Rotation definition states that release of a regular pilot for a break in duty at base will not end their rotation. Is there another reference that states the rotation is illegal if built with a domicile layover?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["open_time", "rotation_definition", "domicile_layover", "legality"],
    mustInclude: ["open time rotation", "domicile layover", "rotation definition", "illegal"],
    mustNotInclude: ["it is illegal without source"],
    shouldAskClarification: false,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "2",
        terms: ["rotation", "break in duty", "base"],
        required: true,
        role: "primary",
      },
      {
        source: "Scheduler Manual",
        terms: ["open time", "domicile layover", "rotation"],
        required: false,
        role: "secondary",
      },
    ],
    riskLevel: "high",
    expectedAnswerNotes: ["Should not label the construction illegal unless there is a source beyond the bare definition text."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-010",
    category: "real_world_fb_scenarios",
    question: "Are we able to drop a May bid period trip for a Silver Slip carry-out from April that overlaps with the May trip? Example: drop May 2nd for a Silver Slip on May 1, April carry-out.",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["silver_slip", "bid_period_crossover", "carryout", "drop_trip"],
    mustInclude: ["May bid period", "Silver Slip", "April carry-out", "overlap", "drop"],
    mustNotInclude: ["always allowed"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "Scheduler Manual",
        terms: ["PCS processing", "Silver Slip carry-out", "carry-out", "bid period", "drop", "overlap"],
        required: false,
        role: "primary",
      },
      {
        source: "PWA",
        section: "23",
        terms: ["Silver Slip", "drop", "bid period", "overlap"],
        required: false,
        role: "secondary",
      },
    ],
    riskLevel: "high",
    expectedAnswerNotes: ["Should treat this as a silver-slip crossover/overlap question, not a generic drop rule."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-011",
    category: "real_world_fb_scenarios",
    question: "Trying to swap with the pot a 2-day in May for 3-day trips in May. All the days are black. I assumed since I was picking up an extra day it would go through, but I’m getting capped reserve days. Do I have this set up correctly?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["Scheduler Manual", "PWA"],
    shouldUseAISynthesis: true,
    complexityTags: ["swap_with_pot", "capped_reserve_days", "black_days", "reserve_coverage"],
    mustInclude: ["swap with pot", "capped reserve days", "black days", "extra day"],
    mustNotInclude: ["black days guarantee approval"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "Scheduler Manual",
        terms: ["PCS processing", "swap with pot", "pickup limit", "reserve coverage"],
        required: false,
        role: "primary",
      },
      {
        source: "PWA",
        section: "23",
        terms: ["reserve", "coverage", "swap"],
        required: false,
        role: "secondary",
      },
    ],
    riskLevel: "high",
    expectedAnswerNotes: ["Should discuss black-day display, reserve coverage, and why capped reserve days can still block an extra-day swap."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-012",
    category: "real_world_fb_scenarios",
    question: "Can you swap with the pot a rotation in May for a rotation pickup in April if the coverage works?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["Scheduler Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["swap_with_pot", "bid_period_crossover", "pcs_run", "coverage"],
    mustInclude: ["swap with pot", "May", "April", "coverage", "PCS"],
    mustNotInclude: ["coverage alone decides it"],
    shouldAskClarification: false,
    expectedSupportAnchors: [
      {
        source: "Scheduler Manual",
        terms: ["PCS processing", "PCS run timing", "bid period", "swap with pot"],
        required: false,
        role: "primary",
      },
    ],
    riskLevel: "medium",
    expectedAnswerNotes: ["Should address PCS timing and bid-period crossover mechanics, not just coverage."],
    redFlags: ["unsupported_policy_certainty"],
    referenceAnswerHint: "Explain that April-to-April is April PCS, May-to-May is May PCS, May-to-April is May PCS, and April-to-May is May PCS; timing of independent PCS runs may matter.",
  },
  {
    id: "qa-rw-new-013",
    category: "real_world_fb_scenarios",
    question: "Where can I find references that define medical procedures that do not count for sick lookback, and get smart on the approval process?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: true,
    complexityTags: ["sick_lookback", "medical_procedure", "approval_process", "section_14"],
    mustInclude: ["medical procedures", "sick lookback", "approval process", "Section 14"],
    mustNotInclude: ["medical advice"],
    shouldAskClarification: false,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "14 F",
        terms: ["sickness", "notification", "verification", "lookback"],
        required: false,
        role: "primary",
      },
    ],
    riskLevel: "high",
    expectedAnswerNotes: ["Should point toward Section 14 process/support and avoid giving medical advice."],
    redFlags: ["legal_advice_overreach", "unsupported_policy_certainty"],
    referenceAnswerHint: "Point to PWA Section 14, especially notification/verification of sickness, and suggest DART or DALPA Aeromedical for process confirmation.",
  },
  {
    id: "qa-rw-new-014",
    category: "real_world_fb_scenarios",
    question: "Why did this not process on the 1200 PCS run? I know I must be inputting something wrong.",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["Scheduler Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["pcs_run", "processing_timing", "bid_period"],
    mustInclude: ["1200 PCS run", "processing", "bid period", "timing"],
    mustNotInclude: ["definitely input wrong"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "Scheduler Manual",
        terms: ["PCS", "1200", "bid period", "processing"],
        required: false,
        role: "primary",
      },
    ],
    riskLevel: "medium",
    expectedAnswerNotes: ["Should treat this as PCS timing/processing, not assume user error."],
    redFlags: ["unsupported_policy_certainty"],
    referenceAnswerHint: "Possible answer: 1200 PCS run for May may not have run yet; April and May runs can be separated by a significant time delay.",
  },
  {
    id: "qa-rw-new-015",
    category: "real_world_fb_scenarios",
    question: "Trying to use SUP days from Mar 2027 to IVD next month, and I'm getting the 'Must be same Vacation year' message. Isn't March 2027 in the same Vacation year as May 2026?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: true,
    complexityTags: ["sup_days", "ivd", "vacation_year", "system_message"],
    mustInclude: ["SUP", "IVD", "same Vacation year", "March 2027", "May 2026"],
    mustNotInclude: ["calendar year equals vacation year"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "7",
        terms: ["vacation year", "IVD", "SUP"],
        required: false,
        role: "primary",
      },
    ],
    riskLevel: "medium",
    expectedAnswerNotes: ["Should explain vacation-year versus calendar-year logic without assuming the system is correct."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-new-016",
    category: "real_world_fb_scenarios",
    question: "I was flying a four-day rotation for 21 hours that ended in JFK with a deadhead home the next day. On the last day, we were running about an hour late and MiCrew showed credit time 24:35 while the rotation showed 22:46. I intended to deviate deadhead and fly back to Atlanta same day, but because we were late I didn’t deviate and flew home on my scheduled flight. After the flight closed out, all credit times went back to 21 hours. Could the extra credit have been because the JFK layover became less than 13 hours? Why did it go back to 21?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    complexityTags: ["deadhead", "deviation", "credit_recalculation", "short_layover", "minimum_layover"],
    mustInclude: ["deadhead", "deviation", "credit", "less than 13 hours", "recalculation"],
    mustNotInclude: ["guaranteed extra credit"],
    shouldAskClarification: true,
    expectedSupportAnchors: [
      {
        source: "PWA",
        section: "12",
        terms: ["layover", "rest", "13 hours"],
        required: false,
        role: "primary",
      },
      {
        source: "Compensation Manual",
        terms: ["deadhead", "credit", "deviation", "recalculation"],
        required: false,
        role: "secondary",
      },
    ],
    riskLevel: "high",
    expectedAnswerNotes: ["Should discuss possible rest/layover recalculation and why provisional credit can collapse back after closeout."],
    redFlags: ["unsupported_policy_certainty"],
  },
  {
    id: "qa-rw-batch2-001",
    question: "What is the current requirement for OE notification? Phone call or CNO?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should frame this as an OE notification-method question and stay cautious if the exact source is missing."],
    expectedSupportAnchors: [
      { source: "Scheduler Manual", terms: ["OE", "notification", "CNO", "phone call"], required: false, role: "primary" },
    ],
    redFlags: ["unsupported_policy_certainty", "vague_answer"],
    complexityTags: ["OE", "notification", "CNO"],
    mustInclude: ["OE notification", "phone vs CNO", "contract requirement"],
    shouldAskClarification: false,
  },
  {
    id: "qa-rw-batch2-002",
    question: "If a planned 30-hour rest is lost due to delay but you’re still FAR legal, can they make you operate or must they release you with pay?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should separate FAR legality from any PWA release-with-pay requirement and avoid overpromising."],
    expectedSupportAnchors: [
      { source: "PWA", section: "12", terms: ["rest", "release", "legal"], required: false, role: "primary" },
    ],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["rest", "FAR vs PWA", "release", "pay"],
    mustInclude: ["30-hour rest", "FAR vs PWA", "release with pay"],
    mustNotInclude: ["FAR legal means they can always make you operate"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-003",
    question: "Is 9:45 rest legal for a DH-only day off short call or do you need 10 hours?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should analyze the rest requirement and distinguish deadhead-only treatment from an FDP question."],
    expectedSupportAnchors: [
      { source: "PWA", section: "12", terms: ["rest", "deadhead", "short call"], required: false, role: "primary" },
    ],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["short call", "deadhead", "rest"],
    mustInclude: ["rest requirement", "deadhead vs FDP", "Section 12"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-004",
    question: "Do you have to answer scheduling calls while on duty or between flights?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "medium",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should distinguish on-duty communication expectations from an off-duty contact rule."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["contact", "phone", "on duty", "SRH"],
    mustInclude: ["on duty vs off duty", "phone requirement", "ACARS"],
    shouldAskClarification: false,
  },
  {
    id: "qa-rw-batch2-005",
    question: "Can I deviate a deadhead to ATL on the way home if it doesn’t pass through base?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "medium",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should discuss deadhead deviation routing rules and any base limitation."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["deadhead", "deviation", "routing"],
    mustInclude: ["deadhead deviation", "routing rules", "base restriction"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-006",
    question: "If a reroute bleeds into a scheduled SLV, what happens to the SLV pay and assignment?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should treat this as reroute-extension plus SLV handling, not a generic reroute answer."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["reroute", "SLV", "extension"],
    mustInclude: ["reroute extension", "SLV handling", "join day 2"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-007",
    question: "Can swap with pot exceed max pickup?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "medium",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should treat this as swap-with-pot and pickup-limit processing, not a flat yes/no."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["swap with pot", "max pickup"],
    mustInclude: ["swap with pot", "pickup limit"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-008",
    question: "What does the 'N' mean on a Silver Slip?",
    expectedLane: "direct_term_lookup",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "low",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should answer as a term/notation lookup if the notation is grounded in the indexed sources."],
    redFlags: ["deterministic_mismatch", "topic_drift"],
    complexityTags: ["SS", "notation"],
    mustInclude: ["Silver Slip", "status meaning"],
    shouldAskClarification: false,
  },
  {
    id: "qa-rw-batch2-009",
    question: "Where are 23M7 affected pilots shown?",
    expectedLane: "document_section_explanation",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: false,
    riskLevel: "low",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should stay focused on where the 23M7 information is surfaced rather than drifting into the full rule."],
    redFlags: ["topic_drift", "no_contract_reference"],
    complexityTags: ["23M7", "iCrew"],
    mustInclude: ["iCrew location", "23M7 logs"],
    shouldAskClarification: false,
  },
  {
    id: "qa-rw-batch2-010",
    question: "Does a one-day GS generate two 24-hour periods off?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: true,
    riskLevel: "medium",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should discuss GS and any rest/protected-day consequence without assuming the answer."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["green slip", "rest"],
    mustInclude: ["GS", "24-hour rest"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-011",
    question: "Is this rotation illegal based on the timing shown?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should treat this as a legality/timing question and avoid overclaiming without the exact timeline."],
    redFlags: ["unsupported_policy_certainty", "vague_answer"],
    complexityTags: ["rotation legality", "timing"],
    mustInclude: ["duty limits", "legality"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-012",
    question: "Can I pick up a trip that overlaps into next bid period and drop my existing trip?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should discuss bid-period crossover processing, overlap, and drop handling."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["bid period crossover", "pickup", "drop"],
    mustInclude: ["bid period", "overlap", "drop"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-013",
    question: "Can I undo a friend swap by picking up each other's trips?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "medium",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should discuss whether a pickup-based workaround is treated differently from a formal swap reversal."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["swap", "MiCrew"],
    mustInclude: ["swap rules", "pickup workaround"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-014",
    question: "Are you required to check your schedule at the end of short call?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "medium",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should frame this as short-call notification/obligation rather than generic contactability."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["short call", "notification"],
    mustInclude: ["notification obligation", "schedule check"],
    shouldAskClarification: false,
  },
  {
    id: "qa-rw-batch2-015",
    question: "If a QS gets delayed overnight, should it still count as a 2-day and trigger PB?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should discuss QS delay, day-count impact, and PB consequences without promising the result."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["quick slip", "delay", "PB"],
    mustInclude: ["QS delay", "PB days", "duty time"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-016",
    question: "How do PB days work if I pick up a GS while on reserve?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should analyze the GS/PB interaction on reserve rather than answering only one side of the question."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["green slip", "PB", "reserve"],
    mustInclude: ["GS", "PB interaction"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-017",
    question: "How should timecard look if CQ was moved over reserve days after sick call?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should discuss sick time, CQ movement, and any guarantee/timecard effect without overclaiming."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["CQ", "sick", "reserve"],
    mustInclude: ["sick time", "CQ", "guarantee"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-018",
    question: "Is it legal to add a turn after a missed call on reserve?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should discuss reroute/contact timing legality and avoid assuming a missed call automatically permits or bars the turn."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["reroute", "tag on"],
    mustInclude: ["reroute legality", "contact timing"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-batch2-019",
    question: "If I get short call notification on last day of vacation via CNO, do I still need a call?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should discuss short-call notice after vacation and whether CNO or phone contact controls."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["short call", "vacation", "CNO"],
    mustInclude: ["notification timing", "vacation", "call requirement"],
    shouldAskClarification: false,
  },
  {
    id: "qa-rw-batch2-020",
    question: "If a QS trip is shortened mid-rotation, how is total pay calculated?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: ["Should discuss guarantee, reroute/pay treatment, and premium treatment rather than a flat pay answer."],
    redFlags: ["unsupported_policy_certainty"],
    complexityTags: ["QS", "reroute", "pay"],
    mustInclude: ["rotation guarantee", "reroute pay", "premium pay"],
    shouldAskClarification: true,
  },
  {
    id: "qa-rw-regression-thread-isolation-001",
    question:
      "On last day of vacation I got a short call placed in MiCrew at 1100 for an 1800 start the next day. No call, no ARCOS, nothing. I never acknowledged it. Does being inside 18 hours make that valid notification or is that still a missed notification off a non-fly day?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should stay in the short-call notification family even if a prior credit-recalculation question was asked in a different turn.",
      "Should not drift into projected-versus-final credit or timecard recalculation language.",
    ],
    redFlags: ["topic_drift", "unsupported_policy_certainty"],
    complexityTags: ["short call", "vacation", "notification", "MiCrew", "acknowledgment", "ARCOS"],
    mustInclude: ["short call", "notification", "vacation", "MiCrew", "acknowledged"],
    mustNotInclude: ["projected-versus-final credit", "timecard recalculation", "Green Slip (inferred)"],
    shouldAskClarification: false,
    clarificationStyle: "none",
  },
  {
    id: "qa-rw-regression-thread-isolation-002",
    question:
      "Four-day rotation with a JFK deadhead and short layover showed 24:35 projected credit in MiCrew, then reverted to 21:00 at closeout. Why would that happen?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual", "Scheduler Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should stay in the pay/credit consistency family even if a prior short-call notification question was asked in a different turn.",
      "Should not drift into short-call notification or vacation acknowledgement language.",
    ],
    redFlags: ["topic_drift", "unsupported_policy_certainty"],
    complexityTags: ["MiCrew", "projected credit", "final credit", "deadhead", "short layover", "closeout"],
    mustInclude: ["projected credit", "final credit", "deadhead", "closeout recalculation"],
    mustNotInclude: ["short call notification", "vacation", "acknowledged", "CNO"],
    shouldAskClarification: false,
    clarificationStyle: "none",
  },
  {
    id: "qa-rw-regression-paycredit-subscenario-001",
    question:
      "I was rerouted on a trip, and when I finished the trip it was worth less credit due to the reroute. Am I still pay protected for the original pairing?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should treat this as a reroute credit-protection question, not a Silver Slip bank-deposit question.",
    ],
    redFlags: ["topic_drift", "unsupported_policy_certainty"],
    complexityTags: ["reroute", "credit protection", "original pairing", "rotation guarantee", "pay protection"],
    mustInclude: ["reroute", "original pairing", "pay protected", "less credit"],
    mustNotInclude: ["silver slip bank deposit", "bank deposit request", "2 hours deposit"],
    expectedSupportAnchors: [
      { source: "PWA", section: "23 L", terms: ["reroute pay"], required: false, role: "primary" },
      { source: "PWA", section: "4 F", terms: ["rotation guarantee"], required: false, role: "secondary" },
      { source: "Compensation Manual", terms: ["reroute pay", "rotation guarantee"], required: false, role: "secondary" },
    ],
    shouldAskClarification: false,
    clarificationStyle: "none",
  },
  {
    id: "qa-rw-regression-paycredit-subscenario-002",
    question: "iCrew won’t let me deposit 2 hours in my bank. Does SS credit not count?",
    expectedLane: "contract_scenario_retrieval",
    expectedSources: ["PWA", "Compensation Manual"],
    shouldUseAISynthesis: true,
    riskLevel: "high",
    category: "real_world_fb_scenarios",
    expectedAnswerNotes: [
      "Should stay in the Silver Slip bank-deposit sub-scenario and not drift into reroute credit protection.",
    ],
    redFlags: ["topic_drift", "unsupported_policy_certainty"],
    complexityTags: ["bank deposit", "SS credit", "Silver Slip", "bank eligibility"],
    mustInclude: ["bank deposit", "SS credit", "bank eligibility"],
    mustNotInclude: ["original pairing", "pay protected", "rotation guarantee"],
    shouldAskClarification: false,
    clarificationStyle: "none",
  },
];
