import type { RotationChainCandidate, RotationChainLeg } from "../rotationChainBuilder";

export const rotation0983Context = {
  base: "SLC",
  layoverCities: ["DTW", "BOS", "MSP"],
  startDate: "17MAR",
  endDate: "20MAR",
} as const;

export const rotation0983Header = {
  rotationNumber: "0983",
  tripDates: "17MAR - 20MAR",
  totalCreditMinutes: 21 * 60 + 55,
  totalScheduledBlockMinutes: 16 * 60 + 42,
} as const;

export const rotation0983ExpectedUserFacingRoutes = [
  "SLC-DTW",
  "DTW-MSP",
  "MSP-RDU",
  "RDU-RDU",
  "RDU-BOS",
  "BOS-RDU",
  "RDU-MSP",
  "MSP-SAT",
  "SAT-SLC",
] as const;

const fullCandidatePool: RotationChainCandidate[] = [
  {
    sourceScreenshotIndex: 0,
    date: "17MAR",
    flightNumber: "DL2244",
    carrier: "DL",
    departureAirport: "SLC",
    arrivalAirport: "DTW",
    scheduledOut: "1519",
    scheduledIn: "2033",
    scheduledBlock: "3:14",
    turn: "16:55",
    rawSourceLine: "DL2244 SLC-DTW 1519-2033 Blk 3:14",
  },
  {
    sourceScreenshotIndex: 0,
    date: "18MAR",
    flightNumber: "DL2697",
    carrier: "DL",
    departureAirport: "DTW",
    arrivalAirport: "MSP",
    scheduledOut: "1328",
    scheduledIn: "1432",
    scheduledBlock: "2:04",
    turn: "0:46",
    rawSourceLine: "DL2697 DTW-MSP 1328-1432 Blk 2:04",
  },
  {
    sourceScreenshotIndex: 1,
    date: "18MAR",
    flightNumber: "DL2699",
    carrier: "DL",
    departureAirport: "MSP",
    arrivalAirport: "RDU",
    scheduledOut: "1518",
    scheduledIn: "1836",
    scheduledBlock: "2:18",
    turn: "0:55",
    rawSourceLine: "DL2699 MSP-RDU 1518-1836 Blk 2:18",
  },
  {
    sourceScreenshotIndex: 1,
    date: "18MAR",
    flightNumber: "DL2393",
    carrier: "DL",
    departureAirport: "RDU",
    arrivalAirport: "RDU",
    scheduledOut: "1931",
    scheduledIn: "1953",
    scheduledBlock: "0:22",
    turn: "1:48",
    rawSourceLine: "DL2393 RDU-RDU 1931-1953 Blk 0:22",
  },
  {
    sourceScreenshotIndex: 1,
    date: "18MAR",
    flightNumber: "DL2393",
    carrier: "DL",
    departureAirport: "RDU",
    arrivalAirport: "BOS",
    scheduledOut: "2141",
    scheduledIn: "2339",
    scheduledBlock: "1:58",
    turn: "15:33",
    rawSourceLine: "DL2393 RDU-BOS 2141-2339 Blk 1:58",
  },
  {
    sourceScreenshotIndex: 2,
    date: "19MAR",
    flightNumber: "DL2782",
    carrier: "DL",
    departureAirport: "BOS",
    arrivalAirport: "RDU",
    scheduledOut: "1512",
    scheduledIn: "1703",
    scheduledBlock: "1:51",
    turn: "1:16",
    rawSourceLine: "DL2782 BOS-RDU 1512-1703 Blk 1:51",
  },
  {
    sourceScreenshotIndex: 2,
    date: "19MAR",
    flightNumber: "DL1474",
    carrier: "DL",
    departureAirport: "RDU",
    arrivalAirport: "MSP",
    scheduledOut: "1819",
    scheduledIn: "2015",
    scheduledBlock: "2:56",
    turn: "13:18",
    rawSourceLine: "DL1474 RDU-MSP 1819-2015 Blk 2:56",
  },
  {
    sourceScreenshotIndex: 3,
    date: "20MAR",
    flightNumber: "DL2667",
    carrier: "DL",
    departureAirport: "MSP",
    arrivalAirport: "SAT",
    scheduledOut: "0933",
    scheduledIn: "1222",
    scheduledBlock: "2:49",
    turn: "1:16",
    rawSourceLine: "DL2667 MSP-SAT 0933-1222 Blk 2:49",
  },
  {
    sourceScreenshotIndex: 3,
    date: "20MAR",
    flightNumber: "DL930",
    carrier: "DL",
    departureAirport: "SAT",
    arrivalAirport: "SLC",
    scheduledOut: "1338",
    scheduledIn: "1535",
    scheduledBlock: "2:57",
    turn: null,
    rawSourceLine: "DL930 SAT-SLC 1338-1535 Blk 2:57",
  },
  {
    sourceScreenshotIndex: 4,
    date: "19MAR",
    flightNumber: "DL2782",
    carrier: "DL",
    departureAirport: "BOS",
    arrivalAirport: "RDU",
    scheduledOut: "1512",
    scheduledIn: "1703",
    scheduledBlock: "1:51",
    turn: "1:16",
    rawSourceLine: "DUP DL2782 BOS-RDU 1512-1703 Blk 1:51",
  },
  {
    sourceScreenshotIndex: 4,
    date: "19MAR",
    flightNumber: "DL1474",
    carrier: "DL",
    departureAirport: "RDU",
    arrivalAirport: "MSP",
    scheduledOut: "1819",
    scheduledIn: "2015",
    scheduledBlock: "2:56",
    turn: "13:18",
    rawSourceLine: "DUP DL1474 RDU-MSP 1819-2015 Blk 2:56",
  },
  {
    sourceScreenshotIndex: 4,
    date: "20MAR",
    flightNumber: "DL2667",
    carrier: "DL",
    departureAirport: "MSP",
    arrivalAirport: "SAT",
    scheduledOut: "0933",
    scheduledIn: "1222",
    scheduledBlock: "2:49",
    turn: "1:16",
    rawSourceLine: "DUP DL2667 MSP-SAT 0933-1222 Blk 2:49",
  },
  {
    sourceScreenshotIndex: 4,
    date: "19MAR",
    flightNumber: "DL2782",
    carrier: "DL",
    departureAirport: "BOS",
    arrivalAirport: "RDU",
    scheduledOut: "1512",
    scheduledIn: "1703",
    scheduledBlock: "1:51",
    turn: null,
    rawSourceLine: "PARTIAL DUP DL2782 BOS-RDU 1512-1703",
  },
];

export const rotation0983RawFinalOrderedChain: RotationChainLeg[] = [
  {
    index: 1,
    ...fullCandidatePool[2],
  },
  {
    index: 2,
    ...fullCandidatePool[3],
  },
  {
    index: 3,
    ...fullCandidatePool[4],
  },
  {
    index: 4,
    ...fullCandidatePool[5],
  },
  {
    index: 5,
    ...fullCandidatePool[6],
  },
  {
    index: 6,
    ...fullCandidatePool[7],
  },
  {
    index: 7,
    ...fullCandidatePool[8],
  },
  {
    index: 8,
    ...fullCandidatePool[9],
  },
  {
    index: 9,
    ...fullCandidatePool[10],
  },
  {
    index: 10,
    ...fullCandidatePool[11],
  },
  {
    index: 11,
    ...fullCandidatePool[12],
  },
  {
    index: 12,
    ...fullCandidatePool[5],
  },
  {
    index: 13,
    ...fullCandidatePool[6],
  },
];

export const rotation0983AllCandidates: RotationChainCandidate[] = fullCandidatePool;
